#!/bin/bash

# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2022 Chris Dragan

set -euo pipefail

UNAME=$(uname -s)

case "$UNAME" in
    Linux)                JOBS=$(grep -c ^processor /proc/cpuinfo) ;;
    Darwin)               JOBS=$(sysctl -n hw.ncpu) ;;
    CYGWIN*|MINGW*|MSYS*) JOBS="$NUMBER_OF_PROCESSORS" ;;
    *)                    JOBS=2 ;;
esac

echo "Using $JOBS jobs"

make clean
make -j $JOBS -k

make clean
make -j $JOBS debug=1

make clean
make -j $JOBS debug=1 imgui=1

make clean
make -j $JOBS debug=1 stdlib=1 test
