#!/bin/bash

# SPDX-License-Identifier: MIT
# Copyright (c) 2021 Chris Dragan

UNAME=$(uname)

[[ $UNAME = Linux ]] && JOBS=$(grep -c ^processor /proc/cpuinfo)
[[ $UNAME = Darwin ]] && JOBS=$(sysctl -n hw.ncpu)

echo "Using $JOBS jobs"

make -j $JOBS
