#!/bin/sh

# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Chris Dragan

set -e

CC="$1"
shift

SRC=$(mktemp -t have_libdecor_XXXXXX.c)
EXE=$(mktemp -t have_libdecor_XXXXXX)

echo "#include <libdecor-0/libdecor.h>" > "$SRC"
echo "int main() { return libdecor_frame_set_app_id ? 0 : 1; }" >> "$SRC"

if "$CC" "$@" -o "$EXE" "$SRC" -ldecor-0 >/dev/null 2>&1; then
    echo "true"
fi

rm -f "$SRC" "$OBJ"
