name: Tests

on:
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true
      - name: Test
        run: ./runtests

  macos:
    runs-on: macos-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true
      - name: Test
        run: ./runtests

  windows:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc
          path-type: inherit
      - name: Remove link.exe from MSYS2
        shell: msys2 {0}
        run: rm -f /bin/link.exe
      - uses: actions/checkout@v4
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true
      - name: Test
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          msys2 -c ./runtests
