name: Tests

on:
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - name: Install Vulkan SDK
        run: |
          sudo apt-get update
          sudo apt-get install libvulkan-dev glslang-tools
      - name: Test
        run: ./runtests

  macos:
    runs-on: macos-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vulkan SDK
        id: cache-vulkansdk
        uses: actions/cache@v1
        with:
          path: "vulkansdk-macos-1.2.198.1"
          key: vulkansdk-macos-1.2.198.1
      - name: Install Vulkan SDK
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.2.198.1/mac/vulkansdk-macos-1.2.198.1.dmg?Human=true -O vulkansdk-macos-1.2.198.1.dmg
          hdiutil attach vulkansdk-macos-1.2.198.1.dmg
          sudo /Volumes/vulkansdk-macos-1.2.198.1/InstallVulkan.app/Contents/MacOS/InstallVulkan --root $GITHUB_WORKSPACE/vulkansdk-macos-1.2.198.1 --accept-licenses --default-answer --confirm-command install
          hdiutil detach /Volumes/vulkansdk-macos-1.2.198.1
      - name: Test
        run: |
          export VULKAN_SDK=`pwd`/vulkansdk-macos-1.2.198.1/macOS
          export PATH="$PATH:$VULKAN_SDK/bin"
          ./runtests
